### ISSUE TITLE
No tasks appear

### ISSUE THREAD

**Issue by RichardDavies** [bajcmartinez/google-tasks-ui#25]
**Describe the bug**
After logging in, the UI loads and the scroll bar at the top under the header scrolls indefinitely, but none of my tasks ever appear.

**To Reproduce**
1. Go to https://googletasksui.com/
2. Log in with my google account
3. Watch the animated scroll bar until you get tired of waiting for any tasks to appear
4. The browser console reports several Content Security Policy errors and TypeError: r is undefined GoogleTasks.ts:172:4

**Screenshots**
![image](https://user-images.githubusercontent.com/13959/63142931-cefefa00-bfa0-11e9-8afa-3c506944373f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 68.0.1

**Comment by bajcmartinez** [comment]
hi, thanks for reporting, one last favor to ask, as I see you are using an adblock and it may be blocking some of the connection. Could you please screenshot the content policy errors, and anything that fails from the network tab?

I'll meanwhile try to reproduce the problem and find a solution.

Thanks again

**Comment by RichardDavies** [comment]
I tried disabling my ad blocker and also tried it in Edge (with no browser plugins installed) and still got the same result. None of the network requests appear to be failing/blocked.

![image](https://user-images.githubusercontent.com/13959/63202879-d1189580-c040-11e9-9a7b-7263170ded7c.png)

![image](https://user-images.githubusercontent.com/13959/63202893-df66b180-c040-11e9-9b33-8435c264e316.png)

**Comment by bajcmartinez** [comment]
I was able to identify and fix a problem that would give that error. Now I can't reproduce it anymore. It has to do with the fact that a user task list was empty.
That's already deployed, if it fixes the problem we can close the ticket, otherwise, I'll keep testing it.

**Comment by RichardDavies** [comment]
Yes, it seems to be working now for me. Thank you!
